server:
  port: 9090
spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      settings:
        trace: false

---
spring:
  profiles:
    active: dev

---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  config:
    activate:
      on-profile: dev

---
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/online-bank
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
    show-sql: true
  config:
    activate:
      on-profile: prod